// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR_YRPLvib42AyTNnV4ru1jEVpsVfNFy4',
    appId: '1:664940196793:web:7dacbd40f85af9d0847c68',
    messagingSenderId: '664940196793',
    projectId: 'flutterapp-8d687',
    authDomain: 'flutterapp-8d687.firebaseapp.com',
    storageBucket: 'flutterapp-8d687.firebasestorage.app',
    measurementId: 'G-JX3FB1TZ4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_K1fOXZxW3sjVn9_SCllZdjJpqW6_A4w',
    appId: '1:664940196793:android:97fe3c9509d7aaf6847c68',
    messagingSenderId: '664940196793',
    projectId: 'flutterapp-8d687',
    storageBucket: 'flutterapp-8d687.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMgm13gOQ3KTsax0Ba0BrPS6RiHcm72tM',
    appId: '1:664940196793:ios:d3030ec44cf967a7847c68',
    messagingSenderId: '664940196793',
    projectId: 'flutterapp-8d687',
    storageBucket: 'flutterapp-8d687.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMgm13gOQ3KTsax0Ba0BrPS6RiHcm72tM',
    appId: '1:664940196793:ios:d3030ec44cf967a7847c68',
    messagingSenderId: '664940196793',
    projectId: 'flutterapp-8d687',
    storageBucket: 'flutterapp-8d687.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR_YRPLvib42AyTNnV4ru1jEVpsVfNFy4',
    appId: '1:664940196793:web:c281f0586cc59c50847c68',
    messagingSenderId: '664940196793',
    projectId: 'flutterapp-8d687',
    authDomain: 'flutterapp-8d687.firebaseapp.com',
    storageBucket: 'flutterapp-8d687.firebasestorage.app',
    measurementId: 'G-GTJWW5NQCD',
  );
}
